### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by fxhaaa** [OpenGVLab/CaFo#9]
Traceback (most recent call last):
  File "C:\Users\fengxiaohu\Downloads\Compressed\FSL\Prompt\CaFo-main\main.py", line 276, in <module>
    main()
  File "C:\Users\fengxiaohu\Downloads\Compressed\FSL\Prompt\CaFo-main\main.py", line 175, in main
    assert (os.path.exists(args.config))
  File "C:\Users\fengxiaohu\Anaconda3\envs\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
如何解决呢？感谢回复

**Comment by AtharvaJadhav7** [comment]
you have to run python file with --config value while running i.e in repo there are various config files in cofigs folder, pass it as an cofig argument while running main file like below
python main.py --config config_name.yaml

**Comment by caoziyang1997** [comment]
> you have to run python file with --config value while running i.e in repo there are various config files in cofigs folder, pass it as an cofig argument while running main file like below python main.py --config config_name.yaml

I'd like to ask about how to download the ImageNet dataset. The ImageNet dataset I downloaded is causing errors when I run it. Is it possible for you to share with me a pre-downloaded ImageNet dataset? I would be very grateful. And the errors is "RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in DATA/imagenet/images."
